apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
  namespace: fortis
  labels:
    app: user-profile
    service: user-profile
spec:
  type: ClusterIP
  selector:
    app: user-profile
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP